name: Elasticsearch Almaren
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name : Check out repository code
        uses: actions/checkout@v2
      - name: Setup ElasticSearch
        uses: getong/elasticsearch-action@v1.2
        with:
          elasticsearch version: '8.4.2'
          host port: 9200
          container port: 9200
          host node port: 9300
          node port: 9300
          discovery type: 'single-node'
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: 8
            cache: sbt
      - name: Build and test scala version
        run: |
          sbt ++2.12.10 test
          sbt ++2.13.9 test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
